version: '3.8'

# This Docker Compose file defines the standalone ELK (Elasticsearch, Logstash, Kibana)
# and Filebeat stack for centralized logging, matching your specified file structure.

services:
  elasticsearch:
    image: elasticsearch:8.14.0
    container_name: aisavvy-elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - xpack.security.enabled=false # Disabling security for local dev
    volumes:
      # Correct path based on your structure
      - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - elk

  logstash:
    image: logstash:8.14.0
    container_name: aisavvy-logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      # Corrected paths based on your structure
      - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ls_data:/usr/share/logstash/data
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: kibana:8.14.0
    container_name: aisavvy-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      # Correct path based on your structure
      - ./elk-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - kb_data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: elastic/filebeat:8.14.0
    container_name: aisavvy-filebeat
    user: root # Required to access Docker socket logs
    volumes:
      # Corrected path based on your structure
      - ./filebeat-config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      # Mount Docker socket and log directories to discover other containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - filebeat_data:/usr/share/filebeat/data
    networks:
      - elk
    depends_on:
      - logstash

networks:
  elk:
    driver: bridge

volumes:
  es_data:
    driver: local
  ls_data:
    driver: local
  kb_data:
    driver: local
  filebeat_data:
    driver: local
