# filebeat.yml

# Configure Filebeat to discover and read logs from Docker containers.
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

# Send all collected logs to our Logstash service.
output.logstash:
  hosts: ["logstash:5044"]

# Optional: Enable the Filebeat dashboard in Kibana (for future use)
setup.kibana:

# Optional: For monitoring Filebeat itself
#http.enabled: true
#http.port: 5066
